### ISSUE TITLE
Remove `out` and `include` folders from .gitignore

### ISSUE THREAD

**Issue by AridAjd** [astrealRBLX/RoUI3#5]
Since the .gitignore file includes the `out` and `include` folders, they do not get published to GitHub. As a result, there's no chance of downloading the plugin "alternatively" using roblox-ts.

**Comment by astrealRBLX** [comment]
The `out` and `include` folders are generated by `npm` after dependencies are installed. I won't include these in the source code since they are generated and not static files. This is the same reason I don't include `node_modules`. You need to first use `npm` to install the packages RoUI3 depends on, then build with roblox-ts, and finally build an output file with Rojo.

**Comment by AridAjd** [comment]
> The `out` and `include` folders are generated by `npm` after dependencies are installed. I won't include these in the source code since they are generated and not static files. This is the same reason I don't include `node_modules`. You need to first use `npm` to install the packages RoUI3 depends on, then build with roblox-ts, and finally build an output file with Rojo.

It doesn't. The out and include folders don't get installed.

**Comment by astrealRBLX** [comment]
You're right I worded that wrong that's my mistake. `npm` will generate `node_modules` and then roblox-ts will generate those folders once you build with `rbxtsc`. I have just downloaded a copy of the repository myself to try and it worked perfectly. I also package releases to upload onto the Roblox Marketplace directly like this. The `out` folder is the transpiled typescript generated by roblox-ts.
